sudo: required
language: node_js
node_js: 8
branches:
  only:
    - master
    - /^v[0-9]/
before_install:
  - ./install.sh 0
script:
  - ./build.sh
  - ls -lh dist
  - node test_snudown.js
deploy:
  - provider: releases
    api_key:
      secure: HZNL8QnRFxJbB/2pMCruV/K1BnPk7q1qNWcAoCuI14K74cDlMjCUv+b1dgXg1Vcx6zBq6ob8cqjptCcsyVur2JK4bfPfwwwuAmlu1DlMfsd0DdCrHmVIWdcGrkqRmvt+1SieyIcQFarQQXU1clLdcneXiAmnFn5VvYv/YrCtc498TLpKSHAVPYXb2vHSHL4JqeXw70BWA11v2IXvzmXhMVoZmlDcZ5nfFCZaF5CTSiNcbkomWZdJYuLDiUn0W6kTpLEh+LUxteOCGKpy/D4fXkatEYGFs2iHfG25WX0RVSsw7Y7flplsPRX6voCPhpdH7Sv4C+j9Snq1yQ6Jpg7FpNO52V4QRdWUH4W1SUfxeNhrA2RvsAxdKlywbZ19ow5t0FdhHt1K5NoyDC8n9d3ufSHAMU14XdQB8Wyv0YT1+ykv7FychkIAAUiXPX8Pv6E0yw3R9cYE0vfs4Apu6yOtVq4s0vfG8Rjz9yiAS1XE1vUj2M5NqK6kOXLLpwsdBI7mTSAWkuvc6cQUBzgG9GNWPgKP1xeQXSEE1auXZoXaHLUTME6dQYT3cOn099gAU1m9yEfPTm26yJtZcrBtID2K3sLlQ3Eg0s0+SoPfxZczomLb2hkmd4TiP6BeCcG+8psArSt/apUFnrb8PNP36ebV5QtayeYwWuT27YIAJM9g53o=
    file:
      - dist/snudown.js
      - dist/snudown_sync.js
      - dist/snudown_async.js
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: 'public@erikdesjardins.io'
    api_key:
      secure: fQuCjkeapl3TFFYwRKTtwzesIheOD0iO0gP+1r9sW+h63seEUybf4MMxFxcPMeMv4hfadBKQTNdNI8YlHBIsWKS9Y4aAnhRCS5O4w+u3uZ6uw/HKNb4bwQ8A6oeU/XaWTPHmeoJq0X5fMAGqZKj+VWIdpDYSDraROEY/CqQv1MSfDayTX0yM/D95GOkW/XTbBXGhNcQwd7VnHYEUAdrdJSpvv8DmUpizQTO7JlNHF5rEuARrLpvBTdss7Gj1ALhEfSP9cj4a+JFdynro+oJz4+t+j7xoVECC1RvXWKw8oBLYqy+80Q9w+niIGtxybN8+hm3oF9ekoyB3lER5K83g4BIWDHFTvlbMkWrorI4PH7DIvF3bhF391wcFtu8xMGIcU5Ar42w7bJqdv/bssFdKsWn9kDVXT1GDqItWFyy8DK9pKgXUzdk6WJhE4jgEU8SmtVL/7FVRDbu87ffWgedtyfgQfeibVvSwDpaZB/D9+0yQuoeioel5nC7F12UHtcmTnvZGOsLIZrkqF743/eDVjA7f0HAq6I8mkNlZXOD+D6MIHZ5DNgEnvPB8VCK0wXZhvzjcyMywzODDpTd6kq6WxgIsLu2FcBcOirycrGKVH50LHWRyosnTgj4OipEqOwL7AZ3wEG2ZCqjMpCl1hACz4fTBv9TjUawmMlUWYg1p8dA=
    skip_cleanup: true
    on:
      tags: true
